spring: 
    application: 
        name: meitemayikt-member #服务的名称,注意服务名称不能包含下划线_
    cloud: 
        nacos: 
            discovery: 
                server-addr: 127.0.0.1:8848 #nacos注册中心的地址
server: 
    port: 8081